# Generated by Django 4.1.7 on 2023-04-18 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EasyLearn', '0002_chapter_content_course_enrollment_delete_post_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonBlocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='БлокиКурса', to='EasyLearn.course')),
            ],
        ),
        migrations.RemoveField(
            model_name='content',
            name='chapter',
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
